Repository NOWSOPT-React-Study-Project/Client, pull requests merged in 2024-06, with the labels that each got.

#24 [Feat] localStorage
  note-app/src/Router.tsx
  note-app/src/hooks/hook.ts
  note-app/src/hooks/useFetchData.ts
  note-app/src/pages/EditPage/EditPage.tsx
  note-app/src/pages/MainPage/MainPage.tsx
  note-app/src/pages/MainPage/MemoList/MemoList.style.ts
  note-app/src/pages/MainPage/MemoList/MemoList.tsx
  note-app/src/pages/ViewPage/ViewPage.tsx
  note-app/src/pages/WritingPage/WritingPage.style.ts
  note-app/src/pages/WritingPage/WritingPage.tsx
  note-app/src/utils/date.ts
  yarn.lock
Labels: ✨ Feat

#30 [Feat] filtering
  note-app/src/components/DropDown/DropDown.tsx
  note-app/src/constants/filter.ts
  note-app/src/pages/MainPage/MainPage.tsx
  note-app/src/pages/MainPage/Pagination/Pagination.tsx
  note-app/src/pages/MainPage/SearchBar/SearchBar.style.ts
  note-app/src/pages/MainPage/SearchBar/SearchBar.tsx
  note-app/src/utils/sort.ts
Labels: ✨ Feat

#27 [Feat] 즐겨찾기 UI
  note-app/src/hooks/useFetchData.ts
  note-app/src/pages/MainPage/MemoList/MemoList.style.ts
  note-app/src/pages/MainPage/MemoList/MemoList.tsx
Labels: ✨ Feat, 다은

#29 [Fix] 컴포넌트 고정위치 수정
  note-app/src/pages/MainPage/MainPage.style.ts
  note-app/src/pages/MainPage/MainPage.tsx
Labels: 다은, ⚒️ fix
